### ISSUE TITLE
"Deploying DynamoDB Locally on your computer" Steps Not Working for Docker

### ISSUE THREAD

**Issue by jamesmcguirepro** [awsdocs/amazon-dynamodb-developer-guide#297]
Following the directions in the "[Deploying DynamoDB locally on your computer](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html)" guide for Docker, DynamoDB local will not work.  The service will hang any time it is called.

Creating a `docker-compose.yml` file like this one:
```
version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
```

will lead to a DynamoDB service that hangs.  This is because the service is running as `dynamodblocal` user, but the volume is mounted without write permissions for the `dynamodblocal` user.

Here is what the log file will output:
```
Oct 13, 2022 6:11:44 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] SQLiteQueue[AKIAI2Z3EJEY54FWNJDA_test.db]: stopped abnormally, reincarnating in 3000ms
Oct 13, 2022 6:11:47 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] cannot open DB[4]: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
Oct 13, 2022 6:11:47 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[AKIAI2Z3EJEY54FWNJDA_test.db]: error running job queue
com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
   at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1480)
   at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
   at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
   at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
   at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
   at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
   at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
   at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
   at java.lang.Thread.run(Thread.java:748)
```

Here's what happens if you open a console in the `dynamodb-local` container:
```
sh-4.2$ pwd
/home/dynamodblocal
sh-4.2$ ls -l | grep data
drwxr-xr-x 2 root root    4096 Oct 13 17:59 data
sh-4.2$ whoami
dynamodblocal
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
